### ISSUE TITLE
Detect Webcam Usage?

### ISSUE THREAD

**Issue by haydndup** [pathartl/TeamsPresence#1]
I installed this today and it's working great - thanks! My previous implementation tailed the log file, and that was not very reliable.

I was wondering if there is a way to also capture if webcam is active? There is an approach described here:
https://community.home-assistant.io/t/microsoft-teams-status/202388/61

This would be really useful to indicate to others when your video is on, and can be used for some automations (like changing lighting if webcam is on).

**Comment by pathartl** [comment]
The registry trick looks like a reliable and known way of detecting usage, so it should be straightforward to implement. I'll take a crack at it when I get some time.

**Comment by haydndup** [comment]
Amazing, thanks!

**Comment by pathartl** [comment]
I implemented a separate polling thread that should look at the registry for any app that has value "LastUsedTimeStop" of 0. It will also report the app's name to HA as a separate entity. The config file has changed a bit so it will have to be regenerated. I won't do a new release just yet until I can fix crashing related to improper config files.

**Comment by pathartl** [comment]
Decided against putting more time into config file checking. A new release has been posted. You will have to remove the existing config and start the application to generate a new one.

https://github.com/pathartl/TeamsPresence/releases/tag/v2.1.0
